### ISSUE TITLE
ajax script link should use https

### ISSUE THREAD

**Issue by phlemoine** [amzn/pay-with-amazon-express-demo#12]
line 7 of java/ExpressPaymentsDemo/web/ExpressPayment.jsp
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
should use https instead

**Comment by alejandrosuarez** [comment]
The author shouldChange to HTTPS

**Comment by islandskater43** [comment]
Thanks @phlemoine & @alejandrosuarez !
