### ISSUE TITLE
OrderReferenceNotification

### ISSUE THREAD

**Issue by wlinder** [amzn/pay-with-amazon-express-demo#2]
I'm not getting an OrderReferenceNotification IPN (only AuthorizationNotification and CaptureNotification IPN's).  Should I be expecting an OrderReferenceNotification IPN?  Thanks.

**Comment by dbrent-amazon** [comment]
The only two notifications you get from Express are Authorize and Capture.

**Comment by dbrent-amazon** [comment]
We are currently looking at the workflow. I would assume you would get the OrderReference notification but it may depend on the CaptureNow flag. We are looking in to it.

**Comment by dbrent-amazon** [comment]
Can you close the order in Seller Central and see if you receive the notification?

**Comment by wlinder** [comment]
I closed the order and received an OrderReferenceNotification IPN.  Just now learning Amazon Payments, so I'm not sure what that gets me, but it is definitely good to know.  Thanks for the help.

**Comment by wlinder** [comment]
Since the sellerorderid identifies the order in my database, it would be nice to get the OrderReferenceNotification first.  I need to update my database with the fees that are included in the other 2 notifications, but I don't have the sellerorderid when those IPNs arrive.  So, I'll have to make API calls at the end of the flow in order to update my database with the fees.
