### ISSUE TITLE
Preserve OrderId in the Event of User Cancellation

### ISSUE THREAD

**Issue by wlinder** [amzn/pay-with-amazon-express-demo#3]
When the user cancels the payment flow, amazon redirects him to the returnURL, but without a parameter that identifies the order.  Is there a "state" parameter that I can use to reference my orderId in the event of user cancellation?  If I can get that data off of the querystring, I'll allow the user to restore his session and select a different payment type.  Thanks.

**Comment by shrakuma** [comment]
When a user cancels the payment flow or abandons the cart, they would usually click the button "cancel and return to 'your' site" At this point it will return back to your Return URL with the resultCode=Failure&failureCode=BuyerAbandoned&sellerId='YOUR_SELLER_ID' in the URL

At this point the Amazon Order ID is still in Draft state. Hence you can technically redirect your user back to the payment widgets page if they still want to make the payment.
