### ISSUE TITLE
Ruby - Blank page

### ISSUE THREAD

**Issue by lucasfais** [amzn/pay-with-amazon-express-demo#4]
I'm trying to use the ruby example, but when I click at "Pay with Amazon" I'm redirected to `https://payments-sandbox.amazon.com/gp/widgets/hosted/init`, blank page and nothing happens.

I checked my settings and they look fine. 

Do you have a guess?

**Comment by khoja-Amazon** [comment]
Thanks for submitting this issue. I am in the process of reproducing your use case. I will be in contact as soon as possible.

**Comment by khoja-Amazon** [comment]
I have sent you instructions on how to register for Login and Pay with Amazon. Please let me know if you have any additional questions.

**Comment by dieudinhleus** [comment]
@samir-khoja , @lucasfais I am trying to use with coldfusion, when I click at button pay with amazon, it is redirected to https://payments-sandbox.amazon.com/gp/widgets/hosted/init.
How to fix it, thanks

**Comment by hrn4n** [comment]
Having the same issue (not using the sample but I don't know where else to ask), getting a blank page @ `https://payments-sandbox.amazon.com/gp/widgets/hosted/init` after generating the signature in my ruby (rails) backend, settings are correct, and I copied the signature function from here, any help would be appreciated
