### ISSUE TITLE
Amazon Payment Response failureCode=InvalidParameterValue when set currencyCode="JPY"

### ISSUE THREAD

**Issue by greenwind1202** [amzn/pay-with-amazon-express-demo#5]
Hi all,
I tried to run your demo project. It works without problem. But when I changed currencyCode from "USD" to "JPY" (Japanese Yen), I got error message:"We're sorry, but there's a problem processing your payment from this website.Your account has not been charged. Please contact seller for assistance." and failureCode=InvalidParameterValue. I guess cause of the error is widgets javascript library, so I figure out some another link:
USA: https://static-na.payments-amazon.com/OffAmazonPayments/us/sandbox/js/Widgets.js
UK: https://static-eu.payments-amazon.com/OffAmazonPayments/uk/sandbox/js/Widgets.js
DE: https://static-eu.payments-amazon.com/OffAmazonPayments/uk/sandbox/js/Widgets.js
But cant figure out widgets javascript for Japan region. I also import above link but still not working. 
What I am doing wrong? Can someone please help me?

**Comment by khoja-amazon** [comment]
Hi, 

The following is the Japan Widgets.js URL:

https://origin-na.ssl-images-amazon.com/images/G/09/EP/offAmazonPayments/sandbox/prod/lpa/js/Widgets.js

Please give this a try and let me know if you run into any issues. I will be happy to help!

**Comment by greenwind1202** [comment]
Hi khoja,

Thank you for your support but it's still not working. Currently, I used information of account which I registered at amazon.com(US) not amazon.co.jp(Japan). So is this cause of issue? I have to use the account in Amazon Japan, right?
By the way, I found a bug. When payment fail, it generate a link "Cancel and Return to the merchant website.". I detected that syntax of href of this link is wrong:
http://localhost:2222/Result.phpresultCode=Failure&amp;sellerId=A24KUKNCGI2O8Z&amp;failureCode=InvalidParameterValue
It miss a question mark "?" between domain and parameters.

**Comment by greenwind1202** [comment]
I've just tried to create a merchant account at amazon.co.jp but I got a trouble:"Sorry, you are not an authorized Seller Central user". How can I register a merchant account?. Please help me to resolve this issue. I am looking forward to hearing from you. Thanks so much.

**Comment by khoja-amazon** [comment]
Hi, 

Yes, you will need to use your amazon.co.jp account information. If you would like to use your amazon.com information, you will need to use the corresponding USA widgets.js URL. I will take a look to see why the "?" is missing from the return URL. I will provide an update as soon as possible.

**Comment by Chirag-Prajapati** [comment]
Hello, I am facing the same issue When I use the currencyCode USD then order place successfully in my website But When I use Currency cod EUR instead of USD then getting error "InvalidParameterValue" Is there any solution for this Error?

**Comment by bjguillot** [comment]
Unfortunately, the Express option (also known as hosted checkout) is currently only available in the North American region.  At this time, the North American region does not support multi-currency payments, so "USD" is the only allowed currency code.  If you are a registered European merchant using a standard (non-Express) integration and still having issues, please contact us through the Seller Central support channels and we can work with you one-on-one to resolve.
