### ISSUE TITLE
How to use amazon recurring payment

### ISSUE THREAD

**Issue by wzhonggo** [amzn/pay-with-amazon-express-demo#6]
Hi all
I know how to use amazon custom fixed payment by this demo , but l do not know how to recurring payment with this demo.I am newer with amazon payment.
Can someone please help me?

**Comment by shrakuma** [comment]
Recurring payments are not currently supported with the express payments which this demo shows. You will need to perform a full integration to get the recurring payments. Please visit the link https://payments.amazon.com/documentation and choose Recurring Payments section for detailed documentation
sample GitHub directory https://amzn.github.io/login-and-pay-with-amazon-sdk-samples/ to view how it can be done. 
The SDK'S are shown in the https://payments.amazon.com/documentation which will be needed to perform the recurring payments

**Comment by wzhonggo** [comment]
Thanks for your response and i am know how to do recurring payments with express payments
