### ISSUE TITLE
php/result.php doesn't validate signature

### ISSUE THREAD

**Issue by rmeden** [amzn/pay-with-amazon-express-demo#7]
The documentation states applications should verify the signature on the return call.  Your example (php/result.php) doesn't do that. 

I've tried coding it myself, but can't get a valid signature.   Maybe you couldn't either?

**Comment by dbrent-amazon** [comment]
I added signature validation to Success.php. I also moved $returnURL into the config file so the domain and path can be parsed to validate the signature. Please let me know if this works for you.

**Comment by rmeden** [comment]
Thanks, your demo works great. But......I found a problem.

if the sellerOrderID contains a special character, it fails authentication.  To test this, update ExpressSignature.php to use a sellerOrderID of "alpha,bravo".  It fails

I plan on using sellerOrderID to pass values back to my application. (I previously used "custom" with the old API)

**Comment by dbrent-amazon** [comment]
Hello, I've made a slight update. sellerOrderId needed to be URL encoded prior to creating the string to sign.

**Comment by rmeden** [comment]
works great, thanks
