### ISSUE TITLE
How to make working for Germany amazon seller account

### ISSUE THREAD

**Issue by dfc2git** [amzn/pay-with-amazon-express-demo#8]
I use https://static-eu.payments-amazon.com/OffAmazonPayments/de/sandbox/js/Widgets.js
I have included returnURL
I got "pay with amazon" button.

But after click Button, I got error
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' on the Amazon Seller Central App Console for Login with Amazon.

response_type=token
client_id=amzn1.application-oa2-client.xxxxxxxxxxxxxxx
scope=payments:hosted
redirect_uri=https://payments-de-sandbox.amazon.com/gp/widgets/hosted/hostedLWAParameter
state={"hostedParamKey":"fc1336ac-7ca2-4956-80bc-fad764cdcaa3"#"lwaClientId":"amzn1.application-oa2-client.xxxxx"#"useAmazonAddressBook":"true"#"UCUIEndPoint":"https://payments-de-sandbox.amazon.com"#"cartOwnerId":"xxxxxxx"}
sandbox=true

Do you know what wrong?

**Comment by seanevan** [comment]
My sincere apologies for the delayed response. The error you have provided indicates that the URL where you are hosting the button from needs to be whitelisted under your Login with Amazon client application. You can accomplish this by logging into Seller Central and selecting the "Login with Amazon" option from the dropdown in the upper right. On the resulting page, please look for the "Allowed JavaScript Origins" and "Allowed Return URLs" fields, and then ensure that you specify the appropriate URLs in these fields. Please let me know if I can help in any other way.

**Comment by wzhonggo** [comment]
Thanks, i has fix it

**Comment by ftendi** [comment]
Hi, I've the same issue.
I'me able to solve this adding "https://payments-de-sandbox.amazon.com/gp/widgets/hosted/hostedLWAParameter" under "Allowed Return URLs" from "Login with Amazon" application settings, but I don't understand why I've to authorize this URL...

Thanks for any help.
